# commit once every 30 days to prevent workflow death
name: Commit to prevent workflow death
on:
  schedule:
    - cron: '0 0 */30 * *'
jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create blank commit
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "example@example.com"
          git commit --allow-empty -m "chore: keep workflows alive"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}